In [18]:
#Importing required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Cleaning the health data

In [2]:
#Installing openpyxl to open excel file
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\homepc\anaconda3\envs\hs_access_env\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\homepc\anaconda3\envs\hs_access_env\lib\site-packages (from openpyxl) (2.0.0)

In [3]:
#Load the data
health_data=pd.read_csv("../Group1-Healthcare_Access_Inequality_Predictor/Data/health_data.csv")

In [4]:
#Displaying the number of rows and columns that are in the data
health_data.shape

(7257, 28)

In [6]:
#Displaying the first row
health_data.head(1)

,Unnamed: 0,facility_type_name,owner_name,owner_type_name,admission_status_name,county,constituency,ward_name,average_rating,facility_services,...,number_of_hdu_beds,number_of_inpatient_beds,number_of_maternity_beds,number_of_isolation_beds,number_of_general_theatres,number_of_maternity_theatres,number_of_minor_theatres,number_of_eye_theatres,new_born_unit,facility_catchment_population
0,2,Dispensary,Ministry of Health,Ministry of Health,Admitting Maternity Patients Only,Trans Nzoia,Endebess,Endebess,0.0,[],...,0,0,2,0,0,0,0,0,False,5000.0

In [7]:
#Dropping the columns that are not needed
health_data_clean=health_data.drop(columns=["new_born_unit","admission_status_name","owner_type_name",
                                            "number_of_hdu_beds","number_of_isolation_beds","number_of_general_theatres",
                                            "number_of_maternity_theatres","number_of_minor_theatres","number_of_eye_theatres",
                                            "admission_status_name",
                                            "sub_county_name","number_of_icu_beds","number_of_emergency_casualty_beds","facility_services","facility_infrastructure"],axis=1)

In [8]:
#Displaying the number of rows and columns that are in the data
health_data_clean.shape

(7257, 14)

In [9]:
#Checking the number of missing enteries per column
health_data_clean.isnull().sum()

Unnamed: 0                          0
facility_type_name                  0
owner_name                          0
county                              0
constituency                        0
ward_name                           0
average_rating                      0
keph_level_name                     0
lat_long                          160
number_of_beds                      0
number_of_cots                      0
number_of_inpatient_beds            0
number_of_maternity_beds            0
facility_catchment_population    4180
dtype: int64

In [11]:
#Saving the data to csv file
health_data_clean.to_csv("../Group1-Healthcare_Access_Inequality_Predictor/Data/health_data_clean.csv")

In [12]:
#Reseting the index of the cleaned data
health_data_clean.reset_index(inplace=True)
health_data_clean

,index,Unnamed: 0,facility_type_name,owner_name,county,constituency,ward_name,average_rating,keph_level_name,lat_long,number_of_beds,number_of_cots,number_of_inpatient_beds,number_of_maternity_beds,facility_catchment_population
0,0,2,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Endebess,0.0,Level 2,"[1.02393, 34.77484]",2,0,0,2,5000.0
1,1,3,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Chepchoina,0.0,Level 2,"[1.1351849999999999, 34.806785]",0,0,0,0,6000.0
2,2,4,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Matumbei,0.0,Level 2,"[1.08089, 34.80747]",3,0,0,3,10426.0
3,3,5,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Endebess,0.0,Level 2,"[1.037451, 34.861203]",3,0,0,3,4579.0
4,4,6,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Chepchoina,0.0,Level 2,"[1.2035879999999999, 34.803397]",3,0,0,3,6459.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7252,7252,16105,Primary care hospitals,Ministry of Health,Taita Taveta,Voi,Mbololo,0.0,Level 4,"[-3.38928, 38.56007]",112,0,0,0,NaN
7253,7253,16106,Primary care hospitals,Ministry of Health,Nandi,Nandi Hills,Nandi Hills,0.0,Level 4,"[0.10404000000000001, 35.18361]",89,5,0,0,NaN
7254,7254,16107,Primary care hospitals,Ministry of Health,Vihiga,Hamisi,Gisambai,0.0,Level 4,"[0.07351, 34.80206]",16,4,0,0,NaN
7255,7255,16108,Primary care hospitals,Ministry of Health,Nandi,Tinderet,Tinderet,0.0,Level 4,"[0.00568, 35.30777]",28,5,0,0,NaN
7256,7256,16109,Primary care hospitals,Ministry of Health,Laikipia,Laikipia West,Rumuruti Township,0.0,Level 4,"[0.27151000000000003, 36.53315]",12,0,0,0,NaN

In [14]:
#Dropping more coulmuns from the dataframe
health_data_clean.drop(columns=["index","Unnamed: 0"],inplace=True)

In [15]:
#Displaying the first five rows of the daraframe
health_data_clean.head()

,facility_type_name,owner_name,county,constituency,ward_name,average_rating,keph_level_name,lat_long,number_of_beds,number_of_cots,number_of_inpatient_beds,number_of_maternity_beds,facility_catchment_population
0,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Endebess,0.0,Level 2,"[1.02393, 34.77484]",2,0,0,2,5000.0
1,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Chepchoina,0.0,Level 2,"[1.1351849999999999, 34.806785]",0,0,0,0,6000.0
2,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Matumbei,0.0,Level 2,"[1.08089, 34.80747]",3,0,0,3,10426.0
3,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Endebess,0.0,Level 2,"[1.037451, 34.861203]",3,0,0,3,4579.0
4,Dispensary,Ministry of Health,Trans Nzoia,Endebess,Chepchoina,0.0,Level 2,"[1.2035879999999999, 34.803397]",3,0,0,3,6459.0

In [16]:
#Displaying the number of rows and columns that are in the data after dropping some columns
health_data_clean.shape

(7257, 13)

In [19]:
#Calculating the mean of the facility catchment population
mean_fcp = health_data_clean["facility_catchment_population"].median()
mean_fcp

np.float64(3220.0)

In [20]:
#Dropping the missing values of the facility catchment population
health_data_clean.dropna(inplace=True)

In [21]:
#Displaying the number of rows and columns that are in the data after dropping the missing rows of facility catchment population
health_data_clean.shape

(3053, 13)

In [22]:
#Checking the number of missing enteries per column
health_data_clean.isnull().sum()

facility_type_name               0
owner_name                       0
county                           0
constituency                     0
ward_name                        0
average_rating                   0
keph_level_name                  0
lat_long                         0
number_of_beds                   0
number_of_cots                   0
number_of_inpatient_beds         0
number_of_maternity_beds         0
facility_catchment_population    0
dtype: int64

In [23]:
#Getting info of the statistical numerical values 
health_data_clean.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
facility_type_name,3053,21,Dispensary,2064,NaN,NaN,NaN,NaN,NaN,NaN,NaN
owner_name,3053,7,Ministry of Health,2894,NaN,NaN,NaN,NaN,NaN,NaN,NaN
county,3053,47,Makueni,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
constituency,3053,284,Makueni,63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ward_name,3053,1072,Township,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
average_rating,3053.0,NaN,NaN,NaN,0.0273,0.276839,0.0,0.0,0.0,0.0,5.0
keph_level_name,3053,5,Level 2,2195,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lat_long,3053,3036,"[0.052869, 34.896204]",2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_of_beds,3053.0,NaN,NaN,NaN,5.802489,27.605629,0.0,0.0,0.0,2.0,650.0
number_of_cots,3053.0,NaN,NaN,NaN,0.624304,2.795456,0.0,0.0,0.0,0.0,58.0
number_of_inpatient_beds,3053.0,NaN,NaN,NaN,3.744841,95.864478,0.0,0.0,0.0,0.0,5213.0
number_of_maternity_beds,3053.0,NaN,NaN,NaN,1.658041,7.009192,0.0,0.0,0.0,0.0,139.0
facility_catchment_population,3053.0,NaN,NaN,NaN,10397.741238,101087.086254,-7.0,1500.0,3213.0,6578.0,5000000.0

In [24]:
# Calculating the sum of all entities in the dataframe and grouping them per county
health_data_aggregate = health_data_clean.groupby('county').agg({
    'average_rating':'mean',
    'number_of_beds':'sum',
    'number_of_cots':'sum',
    'number_of_inpatient_beds':'sum',
    'number_of_maternity_beds':'sum',
    'facility_catchment_population':'sum',
    'facility_type_name':'count'
}).reset_index()

In [25]:
#Displaying the first five rows of the data frame
health_data_aggregate.head()

,county,average_rating,number_of_beds,number_of_cots,number_of_inpatient_beds,number_of_maternity_beds,facility_catchment_population,facility_type_name
0,Baringo,0.003902,284,16,15,19,204309.0,41
1,Bomet,0.012987,157,19,12,71,398032.0,77
2,Bungoma,0.019748,881,67,295,210,1342280.0,129
3,Busia,0.012500,523,1,219,83,243454.0,35
4,Elgeyo Marakwet,0.050000,237,23,2,67,108943.0,25

In [26]:
#Getting info of the statistical numerical values 
health_data_aggregate.describe().T

,count,mean,std,min,25%,50%,75%,max
average_rating,47.0,0.032395,4.734431e-02,0.0,0.002393,0.0129,0.034523,1.842105e-01
number_of_beds,47.0,376.914894,3.031966e+02,0.0,136.500000,295.0000,571.000000,1.058000e+03
number_of_cots,47.0,40.553191,3.450949e+01,0.0,17.000000,33.0000,62.000000,1.760000e+02
number_of_inpatient_beds,47.0,243.255319,7.845373e+02,0.0,3.500000,39.0000,154.500000,5.298000e+03
number_of_maternity_beds,47.0,107.702128,9.053823e+01,0.0,33.000000,83.0000,182.000000,3.710000e+02
facility_catchment_population,47.0,675410.723404,1.309159e+06,45055.0,225977.000000,375997.0000,671880.500000,9.024658e+06
facility_type_name,47.0,64.957447,4.089114e+01,12.0,32.500000,54.0000,91.000000,1.920000e+02

In [27]:
#Remaning the facity name to the number of the facilities in the county(public and NGOs facilities)
health_data_aggregate.rename(columns={'facility_type_name':'no._of_facilities'},inplace= True)

In [28]:
#Displaying the first fuve rows in the dataframe
health_data_aggregate.head()

,county,average_rating,number_of_beds,number_of_cots,number_of_inpatient_beds,number_of_maternity_beds,facility_catchment_population,no._of_facilities
0,Baringo,0.003902,284,16,15,19,204309.0,41
1,Bomet,0.012987,157,19,12,71,398032.0,77
2,Bungoma,0.019748,881,67,295,210,1342280.0,129
3,Busia,0.012500,523,1,219,83,243454.0,35
4,Elgeyo Marakwet,0.050000,237,23,2,67,108943.0,25

# Cleaning the population 2019 census data

In [29]:
#Loading the pop. census data
census_data = pd.read_excel("../Group1-Healthcare_Access_Inequality_Predictor/Data/Kenya_2019_census.xlsx")

In [30]:
#Displaying the first fuve rows in the census data
census_data.head()

,County,Pop_total,Male,Female,H.H_total,HH_Conventional,HH_Group quarters,Persons per Sq. Km,Unnamed: 8,Unnamed: 9
0,MOMBASA,1208333,610257,598046,378422,376295,2127,5495.008378,NaN,NaN
1,KWALE,866820,425121,441681,173176,172802,374,105.022558,NaN,NaN
2,KILIFI,1453787,704089,749673,298472,297990,482,115.809472,NaN,NaN
3,TANA RIVER,315943,158550,157391,68242,66984,1258,8.335430,NaN,NaN
4,LAMU,143920,76103,67813,37963,34231,3732,22.906165,NaN,0.0

In [64]:
#Changing the font of the county names from uppercase to a normal sentence case
#census_data['County'] = census_data['County'].str.title()

In [59]:
#Dropping the unwanted columns in the census data
census_data.drop(columns=["male","female","h.h_total","hh_conventional","hh_group quarters"],inplace=True)
census_data.drop(columns=["persons per sq. km"],inplace=True)

In [60]:
#Displaying the first fuve rows in the census data after dropping other columns
census_data.head()

           county  pop_total
0         Mombasa    1208333
1           Kwale     866820
2          Kilifi    1453787
3      Tana River     315943
4            Lamu     143920

In [65]:
#Displaying the first fuve rows in the census data after case changing
census_data.head()

           county  pop_total
0         Mombasa    1208333
1           Kwale     866820
2          Kilifi    1453787
3      Tana River     315943
4            Lamu     143920

In [35]:
#Changing the column names from sentence case to lower case to match the health data
#census_data.columns= census_data.columns.str.lower()

In [69]:
#Sorting the counties in alphabetical order to match the health data 
census_data_sorted = census_data.sort_values(by='county')
#Displaying the first five rows in the dataframe after sorting
census_data_sorted.head()

                 county  pop_total
29              Baringo     666763
35                Bomet     875689
38              Bungoma    1670570
39                Busia     893681
27      Elgeyo/Marakwet     454480

In [70]:
#Resseting the 9ndex after sorting the counties 
census_data_sorted.reset_index(inplace=True)
census_data_sorted.head()

   index               county  pop_total
0     29              Baringo     666763
1     35                Bomet     875689
2     38              Bungoma    1670570
3     39                Busia     893681
4     27      Elgeyo/Marakwet     454480

In [71]:
#Dropping the index column
census_data_sorted.drop(columns=["index"],inplace=True)
census_data_sorted.head()

                county  pop_total
0              Baringo     666763
1                Bomet     875689
2              Bungoma    1670570
3                Busia     893681
4      Elgeyo/Marakwet     454480

In [40]:
#Displaying the first fuve rows in the census data after dropping the index column
census_data_sorted.head()

,county,pop_total,male,female,h.h_total,hh_conventional,hh_group quarters,persons per sq. km
0,Baringo,666763,336322,330428,142518,141877,641,60.699676
1,Bomet,875689,434287,441379,187641,187230,411,349.286947
2,Bungoma,1670570,812146,858389,358796,357714,1082,552.448500
3,Busia,893681,426252,467401,198152,197944,208,525.761629
4,Elgeyo/Marakwet,454480,227317,227151,99861,99119,742,149.891529

In [77]:
#Linking(concatenating) the cleaned health data together with the census data
Pop_health_data = pd.concat([census_data_sorted,health_data_aggregate],axis=1)
#Displaying the first fuve rows in the census data after concatenation
Pop_health_data.head()

,county,pop_total,county,average_rating,number_of_beds,number_of_cots,number_of_inpatient_beds,number_of_maternity_beds,facility_catchment_population,no._of_facilities
0,Baringo,666763,Baringo,0.003902,284,16,15,19,204309.0,41
1,Bomet,875689,Bomet,0.012987,157,19,12,71,398032.0,77
2,Bungoma,1670570,Bungoma,0.019748,881,67,295,210,1342280.0,129
3,Busia,893681,Busia,0.012500,523,1,219,83,243454.0,35
4,Elgeyo/Marakwet,454480,Elgeyo Marakwet,0.050000,237,23,2,67,108943.0,25

In [78]:
#Deleting the duplicated county names in the final data after concatenation
Pop_health_data = Pop_health_data.loc[:, ~Pop_health_data.columns.duplicated()]
#Displaying the first five rows
Pop_health_data.head()

,county,pop_total,average_rating,number_of_beds,number_of_cots,number_of_inpatient_beds,number_of_maternity_beds,facility_catchment_population,no._of_facilities
0,Baringo,666763,0.003902,284,16,15,19,204309.0,41
1,Bomet,875689,0.012987,157,19,12,71,398032.0,77
2,Bungoma,1670570,0.019748,881,67,295,210,1342280.0,129
3,Busia,893681,0.012500,523,1,219,83,243454.0,35
4,Elgeyo/Marakwet,454480,0.050000,237,23,2,67,108943.0,25

In [79]:
#Checking the number of missing enteries per column. T(Transpose), flips the rows and columns for easier understanding
Pop_health_data.describe().T

,count,mean,std,min,25%,50%,75%,max
pop_total,47.0,1.012006e+06,6.932427e+05,143920.0,609505.000000,893681.0000,1.156724e+06,4.397073e+06
average_rating,47.0,3.239533e-02,4.734431e-02,0.0,0.002393,0.0129,3.452281e-02,1.842105e-01
number_of_beds,47.0,3.769149e+02,3.031966e+02,0.0,136.500000,295.0000,5.710000e+02,1.058000e+03
number_of_cots,47.0,4.055319e+01,3.450949e+01,0.0,17.000000,33.0000,6.200000e+01,1.760000e+02
number_of_inpatient_beds,47.0,2.432553e+02,7.845373e+02,0.0,3.500000,39.0000,1.545000e+02,5.298000e+03
number_of_maternity_beds,47.0,1.077021e+02,9.053823e+01,0.0,33.000000,83.0000,1.820000e+02,3.710000e+02
facility_catchment_population,47.0,6.754107e+05,1.309159e+06,45055.0,225977.000000,375997.0000,6.718805e+05,9.024658e+06
no._of_facilities,47.0,6.495745e+01,4.089114e+01,12.0,32.500000,54.0000,9.100000e+01,1.920000e+02

In [80]:
#Checking the number of missing enteries per column
Pop_health_data.isnull().sum()

county                           0
pop_total                        0
average_rating                   0
number_of_beds                   0
number_of_cots                   0
number_of_inpatient_beds         0
number_of_maternity_beds         0
facility_catchment_population    0
no._of_facilities                0
dtype: int64

In [82]:
#Saving the data to csv file
Pop_health_data.to_csv("../Group1-Healthcare_Access_Inequality_Predictor/Data/Pop_health_data..csv")